### ISSUE TITLE
Permettre de modifier le code des smart contracts

### ISSUE THREAD

**Issue by grout-r** [Societhy/societhy#20]

**Comment by simonvadee** [comment]
- ajouter un onglet à la création d'organisation qui permet d'inspecter le code qui sera déployé et le rendre personnalisable.
- faire le lien avec un service de compilation de solidity online ?
- ajouter un warning sur la page de l'orga pour dire que le code a été modifié
- ajouter une interface de visualisation du code dans la page de l'orga

--> Doit-on laisser ça ? ça laisse beaucoup de place a des hacks non vérifiable

**Comment by simonvadee** [comment]
dropped at kickoff
