### ISSUE TITLE
Vente de tokens

### ISSUE THREAD

**Issue by jidey43** [Societhy/societhy#22]
t'as mis "token/ico" , j'ai pas compris lulz

**Comment by simonvadee** [comment]
- pouvoir créer son token et en définir les caractéristiques, définir la quantité, le nom, le logo
- intégrer une place de marché via un smart contract ? (chui chaud)
- faire le lien avec la partie "levée de fond" de Cédric
- merger avec le voting system déjà en place

**Comment by simonvadee** [comment]
token properties : 
- name
- shortcut (BTC)
- startup price
- token owned part / entirely tokenized
- does give voting power / other benfit (?) / only capital
- ICO duration
- can be publicly traded / inside the company

views to design :
- token creation 
- token exchange / ico view ?

views to update :
- orga dashboard, see all tokens, token price
- user dashboard, see owned tokens, tokens value
- project coins ?
