### ISSUE TITLE
Gestion des droits

### ISSUE THREAD

**Issue by grout-r** [Societhy/societhy#25]

**Comment by simonvadee** [comment]
- hiérarchie des droits pour que plusieurs users de rangs différents MAIS supérieurs au rang minimal requis puissent avoir accès à des documents/fonctionnalités
- inscrire ces rangs dans le Registry et query le contrat pour checker les droits

**Comment by simonvadee** [comment]
la hiérarchie des droits doit-elle fonctionner avec autre chose que la privacy des documents ?
osef de mettre dans la blockchain
