### ISSUE TITLE
Campagnes de financement des projets

### ISSUE THREAD

**Issue by jidey43** [Societhy/societhy#8]
Une campagne de financement peut avoir différentes sources : ether, bitcoin, euro, dollar..

Définition de l’objectif de la campagne, des clauses si jamais la campagne n’arrive pas à terme, de la durée, des personne autorisées à participer, du ou des bénéficiaires de la campagne.
Les créateurs de la campagne peuvent décider de récompenser les participants en parts de l’organisation/du projet (cf.  2.2.1.5 Vente de tokens)

**Comment by cedricvoinnet** [comment]
J'ai 2 petites questions @grout-r @simonvadee :

1. Est-ce que les dons doivent être fermés une fois la campagne terminée ou il est toujours possible de faire des dons pour la cause qui est proposée?

2. Est-ce que les dons doivent être donné directement ou ils sont donné uniquement à la fin de la campagne et doivent être refund si la campagne n'arrive pas à 100% à la fin du temps?
